version: '2.1'
services:
    shotwell:
        extends:
            file: ~/myproject/git/docker/dbuntu/docker-compose.yml
            service: dbuntu
        volumes:
            - ./:/shotwell
            - ./var/logs/:/var/logs/
        command: /bin/sh -c "/shotwell/build.sh > /var/logs/containner.log 2>&1"
