version: '2.1'
services:
    shotwell:
        build:
            context: .
            dockerfile: Dockerfile
        image: huangyingw/shotwell
        volumes:
            - ./.bashrc:/root/.bashrc
            - ./:/shotwell
            - ./var/logs/:/var/logs/
            - ~/.m2/:/root/.m2/
            - ~/.ssh/:/root/.ssh/
            - ~/BareReps/:/root/BareReps/
            - ~/loadrc/:/root/loadrc/
            - ~/loadrc/gitrc/.gitconfig:/root/.gitconfig
        command: /bin/sh -c "/shotwell/build.sh 2>&1 | tee /var/logs/containner.log"
