/* CommandManager.c generated by valac 0.36.6, the Vala compiler
 * generated from CommandManager.vala, do not modify */

/* Copyright 2016 Software Freedom Conservancy Inc.
 *
 * This software is licensed under the GNU LGPL (version 2.1 or later).
 * See the COPYING file in this distribution.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <gobject/gvaluecollector.h>


#define TYPE_COMMAND_DESCRIPTION (command_description_get_type ())
#define COMMAND_DESCRIPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COMMAND_DESCRIPTION, CommandDescription))
#define IS_COMMAND_DESCRIPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COMMAND_DESCRIPTION))
#define COMMAND_DESCRIPTION_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_COMMAND_DESCRIPTION, CommandDescriptionIface))

typedef struct _CommandDescription CommandDescription;
typedef struct _CommandDescriptionIface CommandDescriptionIface;

#define TYPE_COMMAND (command_get_type ())
#define COMMAND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COMMAND, Command))
#define COMMAND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COMMAND, CommandClass))
#define IS_COMMAND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COMMAND))
#define IS_COMMAND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COMMAND))
#define COMMAND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COMMAND, CommandClass))

typedef struct _Command Command;
typedef struct _CommandClass CommandClass;
typedef struct _CommandPrivate CommandPrivate;

#define TYPE_COMMAND_MANAGER (command_manager_get_type ())
#define COMMAND_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COMMAND_MANAGER, CommandManager))
#define COMMAND_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COMMAND_MANAGER, CommandManagerClass))
#define IS_COMMAND_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COMMAND_MANAGER))
#define IS_COMMAND_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COMMAND_MANAGER))
#define COMMAND_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COMMAND_MANAGER, CommandManagerClass))

typedef struct _CommandManager CommandManager;
typedef struct _CommandManagerClass CommandManagerClass;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _CommandManagerPrivate CommandManagerPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _ParamSpecCommandManager ParamSpecCommandManager;
enum  {
	COMMAND_MANAGER_ALTERED_SIGNAL,
	COMMAND_MANAGER_LAST_SIGNAL
};
static guint command_manager_signals[COMMAND_MANAGER_LAST_SIGNAL] = {0};
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _CommandDescriptionIface {
	GTypeInterface parent_iface;
	gchar* (*get_name) (CommandDescription* self);
	gchar* (*get_explanation) (CommandDescription* self);
};

struct _Command {
	GObject parent_instance;
	CommandPrivate * priv;
};

struct _CommandClass {
	GObjectClass parent_class;
	void (*prepare) (Command* self);
	void (*execute) (Command* self);
	void (*undo) (Command* self);
	void (*redo) (Command* self);
	gboolean (*compress) (Command* self, Command* command);
	gchar* (*get_name) (Command* self);
	gchar* (*get_explanation) (Command* self);
};

struct _CommandPrivate {
	gchar* name;
	gchar* explanation;
	CommandManager* manager;
};

struct _CommandManager {
	GTypeInstance parent_instance;
	volatile int ref_count;
	CommandManagerPrivate * priv;
};

struct _CommandManagerClass {
	GTypeClass parent_class;
	void (*finalize) (CommandManager *self);
};

struct _CommandManagerPrivate {
	gint depth;
	GeeArrayList* undo_stack;
	GeeArrayList* redo_stack;
};

struct _ParamSpecCommandManager {
	GParamSpec parent_instance;
};


static gpointer command_parent_class = NULL;
static CommandDescriptionIface * command_command_description_parent_iface = NULL;
static gpointer command_manager_parent_class = NULL;

GType command_description_get_type (void) G_GNUC_CONST;
gchar* command_description_get_name (CommandDescription* self);
gchar* command_description_get_explanation (CommandDescription* self);
GType command_get_type (void) G_GNUC_CONST;
gpointer command_manager_ref (gpointer instance);
void command_manager_unref (gpointer instance);
GParamSpec* param_spec_command_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_command_manager (GValue* value, gpointer v_object);
void value_take_command_manager (GValue* value, gpointer v_object);
gpointer value_get_command_manager (const GValue* value);
GType command_manager_get_type (void) G_GNUC_CONST;
#define COMMAND_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_COMMAND, CommandPrivate))
enum  {
	COMMAND_DUMMY_PROPERTY
};
Command* command_construct (GType object_type, const gchar* name, const gchar* explanation);
void command_prepare (Command* self);
static void command_real_prepare (Command* self);
void command_execute (Command* self);
static void command_real_execute (Command* self);
void command_undo (Command* self);
static void command_real_undo (Command* self);
void command_redo (Command* self);
static void command_real_redo (Command* self);
gboolean command_compress (Command* self, Command* command);
static gboolean command_real_compress (Command* self, Command* command);
gchar* command_get_name (Command* self);
static gchar* command_real_get_name (Command* self);
gchar* command_get_explanation (Command* self);
static gchar* command_real_get_explanation (Command* self);
CommandManager* command_get_command_manager (Command* self);
void command_internal_set_command_manager (Command* self, CommandManager* manager);
static void command_finalize (GObject * obj);
#define COMMAND_MANAGER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_COMMAND_MANAGER, CommandManagerPrivate))
enum  {
	COMMAND_MANAGER_DUMMY_PROPERTY
};
#define COMMAND_MANAGER_DEFAULT_DEPTH 20
CommandManager* command_manager_new (gint depth);
CommandManager* command_manager_construct (GType object_type, gint depth);
void command_manager_reset (CommandManager* self);
void command_manager_execute (CommandManager* self, Command* command);
static Command* command_manager_top (CommandManager* self, GeeArrayList* stack);
static void command_manager_push (CommandManager* self, GeeArrayList* stack, Command* command);
gboolean command_manager_can_undo (CommandManager* self);
gboolean command_manager_can_redo (CommandManager* self);
CommandDescription* command_manager_get_undo_description (CommandManager* self);
gboolean command_manager_undo (CommandManager* self);
static Command* command_manager_pop (CommandManager* self, GeeArrayList* stack);
CommandDescription* command_manager_get_redo_description (CommandManager* self);
gboolean command_manager_redo (CommandManager* self);
static void g_cclosure_user_marshal_VOID__BOOLEAN_BOOLEAN (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void command_manager_finalize (CommandManager * obj);


gchar* command_description_get_name (CommandDescription* self) {
#line 8 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (IS_COMMAND_DESCRIPTION (self), NULL);
#line 8 "/shotwell/src/CommandManager.vala"
	return COMMAND_DESCRIPTION_GET_INTERFACE (self)->get_name (self);
#line 175 "CommandManager.c"
}


gchar* command_description_get_explanation (CommandDescription* self) {
#line 10 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (IS_COMMAND_DESCRIPTION (self), NULL);
#line 10 "/shotwell/src/CommandManager.vala"
	return COMMAND_DESCRIPTION_GET_INTERFACE (self)->get_explanation (self);
#line 184 "CommandManager.c"
}


static void command_description_base_init (CommandDescriptionIface * iface) {
#line 7 "/shotwell/src/CommandManager.vala"
	static gboolean initialized = FALSE;
#line 7 "/shotwell/src/CommandManager.vala"
	if (!initialized) {
#line 7 "/shotwell/src/CommandManager.vala"
		initialized = TRUE;
#line 195 "CommandManager.c"
	}
}


GType command_description_get_type (void) {
	static volatile gsize command_description_type_id__volatile = 0;
	if (g_once_init_enter (&command_description_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CommandDescriptionIface), (GBaseInitFunc) command_description_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType command_description_type_id;
		command_description_type_id = g_type_register_static (G_TYPE_INTERFACE, "CommandDescription", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (command_description_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&command_description_type_id__volatile, command_description_type_id);
	}
	return command_description_type_id__volatile;
}


Command* command_construct (GType object_type, const gchar* name, const gchar* explanation) {
	Command * self = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
#line 32 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 32 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (explanation != NULL, NULL);
#line 32 "/shotwell/src/CommandManager.vala"
	self = (Command*) g_object_new (object_type, NULL);
#line 33 "/shotwell/src/CommandManager.vala"
	_tmp0_ = name;
#line 33 "/shotwell/src/CommandManager.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 33 "/shotwell/src/CommandManager.vala"
	_g_free0 (self->priv->name);
#line 33 "/shotwell/src/CommandManager.vala"
	self->priv->name = _tmp1_;
#line 34 "/shotwell/src/CommandManager.vala"
	_tmp2_ = explanation;
#line 34 "/shotwell/src/CommandManager.vala"
	_tmp3_ = g_strdup (_tmp2_);
#line 34 "/shotwell/src/CommandManager.vala"
	_g_free0 (self->priv->explanation);
#line 34 "/shotwell/src/CommandManager.vala"
	self->priv->explanation = _tmp3_;
#line 32 "/shotwell/src/CommandManager.vala"
	return self;
#line 243 "CommandManager.c"
}


static void command_real_prepare (Command* self) {
}


void command_prepare (Command* self) {
#line 43 "/shotwell/src/CommandManager.vala"
	g_return_if_fail (IS_COMMAND (self));
#line 43 "/shotwell/src/CommandManager.vala"
	COMMAND_GET_CLASS (self)->prepare (self);
#line 256 "CommandManager.c"
}


static void command_real_execute (Command* self) {
#line 46 "/shotwell/src/CommandManager.vala"
	g_critical ("Type `%s' does not implement abstract method `command_execute'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
#line 46 "/shotwell/src/CommandManager.vala"
	return;
#line 265 "CommandManager.c"
}


void command_execute (Command* self) {
#line 46 "/shotwell/src/CommandManager.vala"
	g_return_if_fail (IS_COMMAND (self));
#line 46 "/shotwell/src/CommandManager.vala"
	COMMAND_GET_CLASS (self)->execute (self);
#line 274 "CommandManager.c"
}


static void command_real_undo (Command* self) {
#line 48 "/shotwell/src/CommandManager.vala"
	g_critical ("Type `%s' does not implement abstract method `command_undo'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
#line 48 "/shotwell/src/CommandManager.vala"
	return;
#line 283 "CommandManager.c"
}


void command_undo (Command* self) {
#line 48 "/shotwell/src/CommandManager.vala"
	g_return_if_fail (IS_COMMAND (self));
#line 48 "/shotwell/src/CommandManager.vala"
	COMMAND_GET_CLASS (self)->undo (self);
#line 292 "CommandManager.c"
}


static void command_real_redo (Command* self) {
#line 51 "/shotwell/src/CommandManager.vala"
	command_execute (self);
#line 299 "CommandManager.c"
}


void command_redo (Command* self) {
#line 50 "/shotwell/src/CommandManager.vala"
	g_return_if_fail (IS_COMMAND (self));
#line 50 "/shotwell/src/CommandManager.vala"
	COMMAND_GET_CLASS (self)->redo (self);
#line 308 "CommandManager.c"
}


static gboolean command_real_compress (Command* self, Command* command) {
	gboolean result = FALSE;
#line 56 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (IS_COMMAND (command), FALSE);
#line 57 "/shotwell/src/CommandManager.vala"
	result = FALSE;
#line 57 "/shotwell/src/CommandManager.vala"
	return result;
#line 320 "CommandManager.c"
}


gboolean command_compress (Command* self, Command* command) {
#line 56 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (IS_COMMAND (self), FALSE);
#line 56 "/shotwell/src/CommandManager.vala"
	return COMMAND_GET_CLASS (self)->compress (self, command);
#line 329 "CommandManager.c"
}


static gchar* command_real_get_name (Command* self) {
	gchar* result = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
#line 61 "/shotwell/src/CommandManager.vala"
	_tmp0_ = self->priv->name;
#line 61 "/shotwell/src/CommandManager.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 61 "/shotwell/src/CommandManager.vala"
	result = _tmp1_;
#line 61 "/shotwell/src/CommandManager.vala"
	return result;
#line 345 "CommandManager.c"
}


gchar* command_get_name (Command* self) {
#line 60 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (IS_COMMAND (self), NULL);
#line 60 "/shotwell/src/CommandManager.vala"
	return COMMAND_GET_CLASS (self)->get_name (self);
#line 354 "CommandManager.c"
}


static gchar* command_real_get_explanation (Command* self) {
	gchar* result = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
#line 65 "/shotwell/src/CommandManager.vala"
	_tmp0_ = self->priv->explanation;
#line 65 "/shotwell/src/CommandManager.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 65 "/shotwell/src/CommandManager.vala"
	result = _tmp1_;
#line 65 "/shotwell/src/CommandManager.vala"
	return result;
#line 370 "CommandManager.c"
}


gchar* command_get_explanation (Command* self) {
#line 64 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (IS_COMMAND (self), NULL);
#line 64 "/shotwell/src/CommandManager.vala"
	return COMMAND_GET_CLASS (self)->get_explanation (self);
#line 379 "CommandManager.c"
}


static gpointer _command_manager_ref0 (gpointer self) {
#line 69 "/shotwell/src/CommandManager.vala"
	return self ? command_manager_ref (self) : NULL;
#line 386 "CommandManager.c"
}


CommandManager* command_get_command_manager (Command* self) {
	CommandManager* result = NULL;
	CommandManager* _tmp0_;
	CommandManager* _tmp1_;
#line 68 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (IS_COMMAND (self), NULL);
#line 69 "/shotwell/src/CommandManager.vala"
	_tmp0_ = self->priv->manager;
#line 69 "/shotwell/src/CommandManager.vala"
	_tmp1_ = _command_manager_ref0 (_tmp0_);
#line 69 "/shotwell/src/CommandManager.vala"
	result = _tmp1_;
#line 69 "/shotwell/src/CommandManager.vala"
	return result;
#line 404 "CommandManager.c"
}


void command_internal_set_command_manager (Command* self, CommandManager* manager) {
	CommandManager* _tmp0_;
	CommandManager* _tmp1_;
#line 73 "/shotwell/src/CommandManager.vala"
	g_return_if_fail (IS_COMMAND (self));
#line 73 "/shotwell/src/CommandManager.vala"
	g_return_if_fail (IS_COMMAND_MANAGER (manager));
#line 74 "/shotwell/src/CommandManager.vala"
	_tmp0_ = self->priv->manager;
#line 74 "/shotwell/src/CommandManager.vala"
	_vala_assert (_tmp0_ == NULL, "this.manager == null");
#line 76 "/shotwell/src/CommandManager.vala"
	_tmp1_ = manager;
#line 76 "/shotwell/src/CommandManager.vala"
	self->priv->manager = _tmp1_;
#line 423 "CommandManager.c"
}


static void command_class_init (CommandClass * klass) {
#line 27 "/shotwell/src/CommandManager.vala"
	command_parent_class = g_type_class_peek_parent (klass);
#line 27 "/shotwell/src/CommandManager.vala"
	g_type_class_add_private (klass, sizeof (CommandPrivate));
#line 27 "/shotwell/src/CommandManager.vala"
	((CommandClass *) klass)->prepare = (void (*) (Command *)) command_real_prepare;
#line 27 "/shotwell/src/CommandManager.vala"
	((CommandClass *) klass)->execute = (void (*) (Command *)) command_real_execute;
#line 27 "/shotwell/src/CommandManager.vala"
	((CommandClass *) klass)->undo = (void (*) (Command *)) command_real_undo;
#line 27 "/shotwell/src/CommandManager.vala"
	((CommandClass *) klass)->redo = (void (*) (Command *)) command_real_redo;
#line 27 "/shotwell/src/CommandManager.vala"
	((CommandClass *) klass)->compress = (gboolean (*) (Command *, Command*)) command_real_compress;
#line 27 "/shotwell/src/CommandManager.vala"
	((CommandClass *) klass)->get_name = (gchar* (*) (Command *)) command_real_get_name;
#line 27 "/shotwell/src/CommandManager.vala"
	((CommandClass *) klass)->get_explanation = (gchar* (*) (Command *)) command_real_get_explanation;
#line 27 "/shotwell/src/CommandManager.vala"
	G_OBJECT_CLASS (klass)->finalize = command_finalize;
#line 448 "CommandManager.c"
}


static void command_command_description_interface_init (CommandDescriptionIface * iface) {
#line 27 "/shotwell/src/CommandManager.vala"
	command_command_description_parent_iface = g_type_interface_peek_parent (iface);
#line 27 "/shotwell/src/CommandManager.vala"
	iface->get_name = (gchar* (*) (CommandDescription *)) command_get_name;
#line 27 "/shotwell/src/CommandManager.vala"
	iface->get_explanation = (gchar* (*) (CommandDescription *)) command_get_explanation;
#line 459 "CommandManager.c"
}


static void command_instance_init (Command * self) {
#line 27 "/shotwell/src/CommandManager.vala"
	self->priv = COMMAND_GET_PRIVATE (self);
#line 30 "/shotwell/src/CommandManager.vala"
	self->priv->manager = NULL;
#line 468 "CommandManager.c"
}


static void command_finalize (GObject * obj) {
	Command * self;
#line 27 "/shotwell/src/CommandManager.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_COMMAND, Command);
#line 28 "/shotwell/src/CommandManager.vala"
	_g_free0 (self->priv->name);
#line 29 "/shotwell/src/CommandManager.vala"
	_g_free0 (self->priv->explanation);
#line 27 "/shotwell/src/CommandManager.vala"
	G_OBJECT_CLASS (command_parent_class)->finalize (obj);
#line 482 "CommandManager.c"
}


GType command_get_type (void) {
	static volatile gsize command_type_id__volatile = 0;
	if (g_once_init_enter (&command_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CommandClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) command_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Command), 0, (GInstanceInitFunc) command_instance_init, NULL };
		static const GInterfaceInfo command_description_info = { (GInterfaceInitFunc) command_command_description_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType command_type_id;
		command_type_id = g_type_register_static (G_TYPE_OBJECT, "Command", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_type_add_interface_static (command_type_id, TYPE_COMMAND_DESCRIPTION, &command_description_info);
		g_once_init_leave (&command_type_id__volatile, command_type_id);
	}
	return command_type_id__volatile;
}


CommandManager* command_manager_construct (GType object_type, gint depth) {
	CommandManager* self = NULL;
	gint _tmp0_;
	gint _tmp1_;
#line 89 "/shotwell/src/CommandManager.vala"
	self = (CommandManager*) g_type_create_instance (object_type);
#line 90 "/shotwell/src/CommandManager.vala"
	_tmp0_ = depth;
#line 90 "/shotwell/src/CommandManager.vala"
	_vala_assert (_tmp0_ > 0, "depth > 0");
#line 92 "/shotwell/src/CommandManager.vala"
	_tmp1_ = depth;
#line 92 "/shotwell/src/CommandManager.vala"
	self->priv->depth = _tmp1_;
#line 89 "/shotwell/src/CommandManager.vala"
	return self;
#line 516 "CommandManager.c"
}


CommandManager* command_manager_new (gint depth) {
#line 89 "/shotwell/src/CommandManager.vala"
	return command_manager_construct (TYPE_COMMAND_MANAGER, depth);
#line 523 "CommandManager.c"
}


void command_manager_reset (CommandManager* self) {
	GeeArrayList* _tmp0_;
	GeeArrayList* _tmp1_;
#line 95 "/shotwell/src/CommandManager.vala"
	g_return_if_fail (IS_COMMAND_MANAGER (self));
#line 96 "/shotwell/src/CommandManager.vala"
	_tmp0_ = self->priv->undo_stack;
#line 96 "/shotwell/src/CommandManager.vala"
	gee_abstract_collection_clear (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, GEE_TYPE_ABSTRACT_COLLECTION, GeeAbstractCollection));
#line 97 "/shotwell/src/CommandManager.vala"
	_tmp1_ = self->priv->redo_stack;
#line 97 "/shotwell/src/CommandManager.vala"
	gee_abstract_collection_clear (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, GEE_TYPE_ABSTRACT_COLLECTION, GeeAbstractCollection));
#line 99 "/shotwell/src/CommandManager.vala"
	g_signal_emit (self, command_manager_signals[COMMAND_MANAGER_ALTERED_SIGNAL], 0, FALSE, FALSE);
#line 542 "CommandManager.c"
}


void command_manager_execute (CommandManager* self, Command* command) {
	Command* _tmp0_;
	GeeArrayList* _tmp1_;
	Command* top_command = NULL;
	GeeArrayList* _tmp2_;
	Command* _tmp3_;
	Command* _tmp4_;
	GeeArrayList* _tmp8_;
	Command* _tmp9_;
	Command* _tmp10_;
	Command* _tmp11_;
	gboolean _tmp12_;
	gboolean _tmp13_;
#line 102 "/shotwell/src/CommandManager.vala"
	g_return_if_fail (IS_COMMAND_MANAGER (self));
#line 102 "/shotwell/src/CommandManager.vala"
	g_return_if_fail (IS_COMMAND (command));
#line 104 "/shotwell/src/CommandManager.vala"
	_tmp0_ = command;
#line 104 "/shotwell/src/CommandManager.vala"
	command_internal_set_command_manager (_tmp0_, self);
#line 107 "/shotwell/src/CommandManager.vala"
	_tmp1_ = self->priv->redo_stack;
#line 107 "/shotwell/src/CommandManager.vala"
	gee_abstract_collection_clear (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, GEE_TYPE_ABSTRACT_COLLECTION, GeeAbstractCollection));
#line 110 "/shotwell/src/CommandManager.vala"
	_tmp2_ = self->priv->undo_stack;
#line 110 "/shotwell/src/CommandManager.vala"
	_tmp3_ = command_manager_top (self, _tmp2_);
#line 110 "/shotwell/src/CommandManager.vala"
	top_command = _tmp3_;
#line 111 "/shotwell/src/CommandManager.vala"
	_tmp4_ = top_command;
#line 111 "/shotwell/src/CommandManager.vala"
	if (_tmp4_ != NULL) {
#line 581 "CommandManager.c"
		Command* _tmp5_;
		Command* _tmp6_;
		gboolean _tmp7_;
#line 112 "/shotwell/src/CommandManager.vala"
		_tmp5_ = top_command;
#line 112 "/shotwell/src/CommandManager.vala"
		_tmp6_ = command;
#line 112 "/shotwell/src/CommandManager.vala"
		_tmp7_ = command_compress (_tmp5_, _tmp6_);
#line 112 "/shotwell/src/CommandManager.vala"
		if (_tmp7_) {
#line 113 "/shotwell/src/CommandManager.vala"
			_g_object_unref0 (top_command);
#line 113 "/shotwell/src/CommandManager.vala"
			return;
#line 597 "CommandManager.c"
		}
	}
#line 117 "/shotwell/src/CommandManager.vala"
	_tmp8_ = self->priv->undo_stack;
#line 117 "/shotwell/src/CommandManager.vala"
	_tmp9_ = command;
#line 117 "/shotwell/src/CommandManager.vala"
	command_manager_push (self, _tmp8_, _tmp9_);
#line 119 "/shotwell/src/CommandManager.vala"
	_tmp10_ = command;
#line 119 "/shotwell/src/CommandManager.vala"
	command_prepare (_tmp10_);
#line 120 "/shotwell/src/CommandManager.vala"
	_tmp11_ = command;
#line 120 "/shotwell/src/CommandManager.vala"
	command_execute (_tmp11_);
#line 123 "/shotwell/src/CommandManager.vala"
	_tmp12_ = command_manager_can_undo (self);
#line 123 "/shotwell/src/CommandManager.vala"
	_tmp13_ = command_manager_can_redo (self);
#line 123 "/shotwell/src/CommandManager.vala"
	g_signal_emit (self, command_manager_signals[COMMAND_MANAGER_ALTERED_SIGNAL], 0, _tmp12_, _tmp13_);
#line 102 "/shotwell/src/CommandManager.vala"
	_g_object_unref0 (top_command);
#line 622 "CommandManager.c"
}


gboolean command_manager_can_undo (CommandManager* self) {
	gboolean result = FALSE;
	GeeArrayList* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
#line 126 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (IS_COMMAND_MANAGER (self), FALSE);
#line 127 "/shotwell/src/CommandManager.vala"
	_tmp0_ = self->priv->undo_stack;
#line 127 "/shotwell/src/CommandManager.vala"
	_tmp1_ = gee_abstract_collection_get_size (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, GEE_TYPE_ABSTRACT_COLLECTION, GeeAbstractCollection));
#line 127 "/shotwell/src/CommandManager.vala"
	_tmp2_ = _tmp1_;
#line 127 "/shotwell/src/CommandManager.vala"
	result = _tmp2_ > 0;
#line 127 "/shotwell/src/CommandManager.vala"
	return result;
#line 643 "CommandManager.c"
}


CommandDescription* command_manager_get_undo_description (CommandManager* self) {
	CommandDescription* result = NULL;
	GeeArrayList* _tmp0_;
	Command* _tmp1_;
#line 130 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (IS_COMMAND_MANAGER (self), NULL);
#line 131 "/shotwell/src/CommandManager.vala"
	_tmp0_ = self->priv->undo_stack;
#line 131 "/shotwell/src/CommandManager.vala"
	_tmp1_ = command_manager_top (self, _tmp0_);
#line 131 "/shotwell/src/CommandManager.vala"
	result = G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, TYPE_COMMAND_DESCRIPTION, CommandDescription);
#line 131 "/shotwell/src/CommandManager.vala"
	return result;
#line 661 "CommandManager.c"
}


gboolean command_manager_undo (CommandManager* self) {
	gboolean result = FALSE;
	Command* command = NULL;
	GeeArrayList* _tmp0_;
	Command* _tmp1_;
	Command* _tmp2_;
	GeeArrayList* _tmp3_;
	Command* _tmp4_;
	Command* _tmp5_;
	Command* _tmp6_;
	gboolean _tmp7_;
	gboolean _tmp8_;
#line 134 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (IS_COMMAND_MANAGER (self), FALSE);
#line 135 "/shotwell/src/CommandManager.vala"
	_tmp0_ = self->priv->undo_stack;
#line 135 "/shotwell/src/CommandManager.vala"
	_tmp1_ = command_manager_pop (self, _tmp0_);
#line 135 "/shotwell/src/CommandManager.vala"
	command = _tmp1_;
#line 136 "/shotwell/src/CommandManager.vala"
	_tmp2_ = command;
#line 136 "/shotwell/src/CommandManager.vala"
	if (_tmp2_ == NULL) {
#line 137 "/shotwell/src/CommandManager.vala"
		result = FALSE;
#line 137 "/shotwell/src/CommandManager.vala"
		_g_object_unref0 (command);
#line 137 "/shotwell/src/CommandManager.vala"
		return result;
#line 695 "CommandManager.c"
	}
#line 140 "/shotwell/src/CommandManager.vala"
	_tmp3_ = self->priv->redo_stack;
#line 140 "/shotwell/src/CommandManager.vala"
	_tmp4_ = command;
#line 140 "/shotwell/src/CommandManager.vala"
	command_manager_push (self, _tmp3_, _tmp4_);
#line 143 "/shotwell/src/CommandManager.vala"
	_tmp5_ = command;
#line 143 "/shotwell/src/CommandManager.vala"
	command_prepare (_tmp5_);
#line 144 "/shotwell/src/CommandManager.vala"
	_tmp6_ = command;
#line 144 "/shotwell/src/CommandManager.vala"
	command_undo (_tmp6_);
#line 147 "/shotwell/src/CommandManager.vala"
	_tmp7_ = command_manager_can_undo (self);
#line 147 "/shotwell/src/CommandManager.vala"
	_tmp8_ = command_manager_can_redo (self);
#line 147 "/shotwell/src/CommandManager.vala"
	g_signal_emit (self, command_manager_signals[COMMAND_MANAGER_ALTERED_SIGNAL], 0, _tmp7_, _tmp8_);
#line 149 "/shotwell/src/CommandManager.vala"
	result = TRUE;
#line 149 "/shotwell/src/CommandManager.vala"
	_g_object_unref0 (command);
#line 149 "/shotwell/src/CommandManager.vala"
	return result;
#line 723 "CommandManager.c"
}


gboolean command_manager_can_redo (CommandManager* self) {
	gboolean result = FALSE;
	GeeArrayList* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
#line 152 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (IS_COMMAND_MANAGER (self), FALSE);
#line 153 "/shotwell/src/CommandManager.vala"
	_tmp0_ = self->priv->redo_stack;
#line 153 "/shotwell/src/CommandManager.vala"
	_tmp1_ = gee_abstract_collection_get_size (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, GEE_TYPE_ABSTRACT_COLLECTION, GeeAbstractCollection));
#line 153 "/shotwell/src/CommandManager.vala"
	_tmp2_ = _tmp1_;
#line 153 "/shotwell/src/CommandManager.vala"
	result = _tmp2_ > 0;
#line 153 "/shotwell/src/CommandManager.vala"
	return result;
#line 744 "CommandManager.c"
}


CommandDescription* command_manager_get_redo_description (CommandManager* self) {
	CommandDescription* result = NULL;
	GeeArrayList* _tmp0_;
	Command* _tmp1_;
#line 156 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (IS_COMMAND_MANAGER (self), NULL);
#line 157 "/shotwell/src/CommandManager.vala"
	_tmp0_ = self->priv->redo_stack;
#line 157 "/shotwell/src/CommandManager.vala"
	_tmp1_ = command_manager_top (self, _tmp0_);
#line 157 "/shotwell/src/CommandManager.vala"
	result = G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, TYPE_COMMAND_DESCRIPTION, CommandDescription);
#line 157 "/shotwell/src/CommandManager.vala"
	return result;
#line 762 "CommandManager.c"
}


gboolean command_manager_redo (CommandManager* self) {
	gboolean result = FALSE;
	Command* command = NULL;
	GeeArrayList* _tmp0_;
	Command* _tmp1_;
	Command* _tmp2_;
	GeeArrayList* _tmp3_;
	Command* _tmp4_;
	Command* _tmp5_;
	Command* _tmp6_;
	gboolean _tmp7_;
	gboolean _tmp8_;
#line 160 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (IS_COMMAND_MANAGER (self), FALSE);
#line 161 "/shotwell/src/CommandManager.vala"
	_tmp0_ = self->priv->redo_stack;
#line 161 "/shotwell/src/CommandManager.vala"
	_tmp1_ = command_manager_pop (self, _tmp0_);
#line 161 "/shotwell/src/CommandManager.vala"
	command = _tmp1_;
#line 162 "/shotwell/src/CommandManager.vala"
	_tmp2_ = command;
#line 162 "/shotwell/src/CommandManager.vala"
	if (_tmp2_ == NULL) {
#line 163 "/shotwell/src/CommandManager.vala"
		result = FALSE;
#line 163 "/shotwell/src/CommandManager.vala"
		_g_object_unref0 (command);
#line 163 "/shotwell/src/CommandManager.vala"
		return result;
#line 796 "CommandManager.c"
	}
#line 166 "/shotwell/src/CommandManager.vala"
	_tmp3_ = self->priv->undo_stack;
#line 166 "/shotwell/src/CommandManager.vala"
	_tmp4_ = command;
#line 166 "/shotwell/src/CommandManager.vala"
	command_manager_push (self, _tmp3_, _tmp4_);
#line 169 "/shotwell/src/CommandManager.vala"
	_tmp5_ = command;
#line 169 "/shotwell/src/CommandManager.vala"
	command_prepare (_tmp5_);
#line 170 "/shotwell/src/CommandManager.vala"
	_tmp6_ = command;
#line 170 "/shotwell/src/CommandManager.vala"
	command_redo (_tmp6_);
#line 173 "/shotwell/src/CommandManager.vala"
	_tmp7_ = command_manager_can_undo (self);
#line 173 "/shotwell/src/CommandManager.vala"
	_tmp8_ = command_manager_can_redo (self);
#line 173 "/shotwell/src/CommandManager.vala"
	g_signal_emit (self, command_manager_signals[COMMAND_MANAGER_ALTERED_SIGNAL], 0, _tmp7_, _tmp8_);
#line 175 "/shotwell/src/CommandManager.vala"
	result = TRUE;
#line 175 "/shotwell/src/CommandManager.vala"
	_g_object_unref0 (command);
#line 175 "/shotwell/src/CommandManager.vala"
	return result;
#line 824 "CommandManager.c"
}


static Command* command_manager_top (CommandManager* self, GeeArrayList* stack) {
	Command* result = NULL;
	Command* _tmp0_ = NULL;
	GeeArrayList* _tmp1_;
	gint _tmp2_;
	gint _tmp3_;
#line 178 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (IS_COMMAND_MANAGER (self), NULL);
#line 178 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (GEE_IS_ARRAY_LIST (stack), NULL);
#line 179 "/shotwell/src/CommandManager.vala"
	_tmp1_ = stack;
#line 179 "/shotwell/src/CommandManager.vala"
	_tmp2_ = gee_abstract_collection_get_size (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, GEE_TYPE_ABSTRACT_COLLECTION, GeeAbstractCollection));
#line 179 "/shotwell/src/CommandManager.vala"
	_tmp3_ = _tmp2_;
#line 179 "/shotwell/src/CommandManager.vala"
	if (_tmp3_ > 0) {
#line 846 "CommandManager.c"
		GeeArrayList* _tmp4_;
		GeeArrayList* _tmp5_;
		gint _tmp6_;
		gint _tmp7_;
		gpointer _tmp8_;
#line 179 "/shotwell/src/CommandManager.vala"
		_tmp4_ = stack;
#line 179 "/shotwell/src/CommandManager.vala"
		_tmp5_ = stack;
#line 179 "/shotwell/src/CommandManager.vala"
		_tmp6_ = gee_abstract_collection_get_size (G_TYPE_CHECK_INSTANCE_CAST (_tmp5_, GEE_TYPE_ABSTRACT_COLLECTION, GeeAbstractCollection));
#line 179 "/shotwell/src/CommandManager.vala"
		_tmp7_ = _tmp6_;
#line 179 "/shotwell/src/CommandManager.vala"
		_tmp8_ = gee_abstract_list_get (G_TYPE_CHECK_INSTANCE_CAST (_tmp4_, GEE_TYPE_ABSTRACT_LIST, GeeAbstractList), _tmp7_ - 1);
#line 179 "/shotwell/src/CommandManager.vala"
		_g_object_unref0 (_tmp0_);
#line 179 "/shotwell/src/CommandManager.vala"
		_tmp0_ = (Command*) _tmp8_;
#line 866 "CommandManager.c"
	} else {
#line 179 "/shotwell/src/CommandManager.vala"
		_g_object_unref0 (_tmp0_);
#line 179 "/shotwell/src/CommandManager.vala"
		_tmp0_ = NULL;
#line 872 "CommandManager.c"
	}
#line 179 "/shotwell/src/CommandManager.vala"
	result = _tmp0_;
#line 179 "/shotwell/src/CommandManager.vala"
	return result;
#line 878 "CommandManager.c"
}


static void command_manager_push (CommandManager* self, GeeArrayList* stack, Command* command) {
	GeeArrayList* _tmp0_;
	Command* _tmp1_;
#line 182 "/shotwell/src/CommandManager.vala"
	g_return_if_fail (IS_COMMAND_MANAGER (self));
#line 182 "/shotwell/src/CommandManager.vala"
	g_return_if_fail (GEE_IS_ARRAY_LIST (stack));
#line 182 "/shotwell/src/CommandManager.vala"
	g_return_if_fail (IS_COMMAND (command));
#line 183 "/shotwell/src/CommandManager.vala"
	_tmp0_ = stack;
#line 183 "/shotwell/src/CommandManager.vala"
	_tmp1_ = command;
#line 183 "/shotwell/src/CommandManager.vala"
	gee_abstract_collection_add (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, GEE_TYPE_ABSTRACT_COLLECTION, GeeAbstractCollection), _tmp1_);
#line 186 "/shotwell/src/CommandManager.vala"
	while (TRUE) {
#line 899 "CommandManager.c"
		GeeArrayList* _tmp2_;
		gint _tmp3_;
		gint _tmp4_;
		gint _tmp5_;
		GeeArrayList* _tmp6_;
		gpointer _tmp7_;
		Command* _tmp8_;
#line 186 "/shotwell/src/CommandManager.vala"
		_tmp2_ = stack;
#line 186 "/shotwell/src/CommandManager.vala"
		_tmp3_ = gee_abstract_collection_get_size (G_TYPE_CHECK_INSTANCE_CAST (_tmp2_, GEE_TYPE_ABSTRACT_COLLECTION, GeeAbstractCollection));
#line 186 "/shotwell/src/CommandManager.vala"
		_tmp4_ = _tmp3_;
#line 186 "/shotwell/src/CommandManager.vala"
		_tmp5_ = self->priv->depth;
#line 186 "/shotwell/src/CommandManager.vala"
		if (!(_tmp4_ >= _tmp5_)) {
#line 186 "/shotwell/src/CommandManager.vala"
			break;
#line 919 "CommandManager.c"
		}
#line 187 "/shotwell/src/CommandManager.vala"
		_tmp6_ = stack;
#line 187 "/shotwell/src/CommandManager.vala"
		_tmp7_ = gee_abstract_list_remove_at (G_TYPE_CHECK_INSTANCE_CAST (_tmp6_, GEE_TYPE_ABSTRACT_LIST, GeeAbstractList), 0);
#line 187 "/shotwell/src/CommandManager.vala"
		_tmp8_ = (Command*) _tmp7_;
#line 187 "/shotwell/src/CommandManager.vala"
		_g_object_unref0 (_tmp8_);
#line 929 "CommandManager.c"
	}
}


static Command* command_manager_pop (CommandManager* self, GeeArrayList* stack) {
	Command* result = NULL;
	GeeArrayList* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	Command* command = NULL;
	GeeArrayList* _tmp3_;
	GeeArrayList* _tmp4_;
	gint _tmp5_;
	gint _tmp6_;
	gpointer _tmp7_;
	gboolean removed = FALSE;
	GeeArrayList* _tmp8_;
	Command* _tmp9_;
	gboolean _tmp10_;
	gboolean _tmp11_;
#line 190 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (IS_COMMAND_MANAGER (self), NULL);
#line 190 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (GEE_IS_ARRAY_LIST (stack), NULL);
#line 191 "/shotwell/src/CommandManager.vala"
	_tmp0_ = stack;
#line 191 "/shotwell/src/CommandManager.vala"
	_tmp1_ = gee_abstract_collection_get_size (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, GEE_TYPE_ABSTRACT_COLLECTION, GeeAbstractCollection));
#line 191 "/shotwell/src/CommandManager.vala"
	_tmp2_ = _tmp1_;
#line 191 "/shotwell/src/CommandManager.vala"
	if (_tmp2_ <= 0) {
#line 192 "/shotwell/src/CommandManager.vala"
		result = NULL;
#line 192 "/shotwell/src/CommandManager.vala"
		return result;
#line 966 "CommandManager.c"
	}
#line 194 "/shotwell/src/CommandManager.vala"
	_tmp3_ = stack;
#line 194 "/shotwell/src/CommandManager.vala"
	_tmp4_ = stack;
#line 194 "/shotwell/src/CommandManager.vala"
	_tmp5_ = gee_abstract_collection_get_size (G_TYPE_CHECK_INSTANCE_CAST (_tmp4_, GEE_TYPE_ABSTRACT_COLLECTION, GeeAbstractCollection));
#line 194 "/shotwell/src/CommandManager.vala"
	_tmp6_ = _tmp5_;
#line 194 "/shotwell/src/CommandManager.vala"
	_tmp7_ = gee_abstract_list_get (G_TYPE_CHECK_INSTANCE_CAST (_tmp3_, GEE_TYPE_ABSTRACT_LIST, GeeAbstractList), _tmp6_ - 1);
#line 194 "/shotwell/src/CommandManager.vala"
	command = (Command*) _tmp7_;
#line 195 "/shotwell/src/CommandManager.vala"
	_tmp8_ = stack;
#line 195 "/shotwell/src/CommandManager.vala"
	_tmp9_ = command;
#line 195 "/shotwell/src/CommandManager.vala"
	_tmp10_ = gee_abstract_collection_remove (G_TYPE_CHECK_INSTANCE_CAST (_tmp8_, GEE_TYPE_ABSTRACT_COLLECTION, GeeAbstractCollection), _tmp9_);
#line 195 "/shotwell/src/CommandManager.vala"
	removed = _tmp10_;
#line 196 "/shotwell/src/CommandManager.vala"
	_tmp11_ = removed;
#line 196 "/shotwell/src/CommandManager.vala"
	_vala_assert (_tmp11_, "removed");
#line 198 "/shotwell/src/CommandManager.vala"
	result = command;
#line 198 "/shotwell/src/CommandManager.vala"
	return result;
#line 996 "CommandManager.c"
}


static void g_cclosure_user_marshal_VOID__BOOLEAN_BOOLEAN (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__BOOLEAN_BOOLEAN) (gpointer data1, gboolean arg_1, gboolean arg_2, gpointer data2);
	register GMarshalFunc_VOID__BOOLEAN_BOOLEAN callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
#line 80 "/shotwell/src/CommandManager.vala"
	g_return_if_fail (n_param_values == 3);
#line 80 "/shotwell/src/CommandManager.vala"
	if (G_CCLOSURE_SWAP_DATA (closure)) {
#line 80 "/shotwell/src/CommandManager.vala"
		data1 = closure->data;
#line 80 "/shotwell/src/CommandManager.vala"
		data2 = param_values->data[0].v_pointer;
#line 1015 "CommandManager.c"
	} else {
#line 80 "/shotwell/src/CommandManager.vala"
		data1 = param_values->data[0].v_pointer;
#line 80 "/shotwell/src/CommandManager.vala"
		data2 = closure->data;
#line 1021 "CommandManager.c"
	}
#line 80 "/shotwell/src/CommandManager.vala"
	callback = (GMarshalFunc_VOID__BOOLEAN_BOOLEAN) (marshal_data ? marshal_data : cc->callback);
#line 80 "/shotwell/src/CommandManager.vala"
	callback (data1, g_value_get_boolean (param_values + 1), g_value_get_boolean (param_values + 2), data2);
#line 1027 "CommandManager.c"
}


static void value_command_manager_init (GValue* value) {
#line 80 "/shotwell/src/CommandManager.vala"
	value->data[0].v_pointer = NULL;
#line 1034 "CommandManager.c"
}


static void value_command_manager_free_value (GValue* value) {
#line 80 "/shotwell/src/CommandManager.vala"
	if (value->data[0].v_pointer) {
#line 80 "/shotwell/src/CommandManager.vala"
		command_manager_unref (value->data[0].v_pointer);
#line 1043 "CommandManager.c"
	}
}


static void value_command_manager_copy_value (const GValue* src_value, GValue* dest_value) {
#line 80 "/shotwell/src/CommandManager.vala"
	if (src_value->data[0].v_pointer) {
#line 80 "/shotwell/src/CommandManager.vala"
		dest_value->data[0].v_pointer = command_manager_ref (src_value->data[0].v_pointer);
#line 1053 "CommandManager.c"
	} else {
#line 80 "/shotwell/src/CommandManager.vala"
		dest_value->data[0].v_pointer = NULL;
#line 1057 "CommandManager.c"
	}
}


static gpointer value_command_manager_peek_pointer (const GValue* value) {
#line 80 "/shotwell/src/CommandManager.vala"
	return value->data[0].v_pointer;
#line 1065 "CommandManager.c"
}


static gchar* value_command_manager_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
#line 80 "/shotwell/src/CommandManager.vala"
	if (collect_values[0].v_pointer) {
#line 1072 "CommandManager.c"
		CommandManager * object;
		object = collect_values[0].v_pointer;
#line 80 "/shotwell/src/CommandManager.vala"
		if (object->parent_instance.g_class == NULL) {
#line 80 "/shotwell/src/CommandManager.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 1079 "CommandManager.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 80 "/shotwell/src/CommandManager.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 1083 "CommandManager.c"
		}
#line 80 "/shotwell/src/CommandManager.vala"
		value->data[0].v_pointer = command_manager_ref (object);
#line 1087 "CommandManager.c"
	} else {
#line 80 "/shotwell/src/CommandManager.vala"
		value->data[0].v_pointer = NULL;
#line 1091 "CommandManager.c"
	}
#line 80 "/shotwell/src/CommandManager.vala"
	return NULL;
#line 1095 "CommandManager.c"
}


static gchar* value_command_manager_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	CommandManager ** object_p;
	object_p = collect_values[0].v_pointer;
#line 80 "/shotwell/src/CommandManager.vala"
	if (!object_p) {
#line 80 "/shotwell/src/CommandManager.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 1106 "CommandManager.c"
	}
#line 80 "/shotwell/src/CommandManager.vala"
	if (!value->data[0].v_pointer) {
#line 80 "/shotwell/src/CommandManager.vala"
		*object_p = NULL;
#line 1112 "CommandManager.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 80 "/shotwell/src/CommandManager.vala"
		*object_p = value->data[0].v_pointer;
#line 1116 "CommandManager.c"
	} else {
#line 80 "/shotwell/src/CommandManager.vala"
		*object_p = command_manager_ref (value->data[0].v_pointer);
#line 1120 "CommandManager.c"
	}
#line 80 "/shotwell/src/CommandManager.vala"
	return NULL;
#line 1124 "CommandManager.c"
}


GParamSpec* param_spec_command_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecCommandManager* spec;
#line 80 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_COMMAND_MANAGER), NULL);
#line 80 "/shotwell/src/CommandManager.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 80 "/shotwell/src/CommandManager.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 80 "/shotwell/src/CommandManager.vala"
	return G_PARAM_SPEC (spec);
#line 1138 "CommandManager.c"
}


gpointer value_get_command_manager (const GValue* value) {
#line 80 "/shotwell/src/CommandManager.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_COMMAND_MANAGER), NULL);
#line 80 "/shotwell/src/CommandManager.vala"
	return value->data[0].v_pointer;
#line 1147 "CommandManager.c"
}


void value_set_command_manager (GValue* value, gpointer v_object) {
	CommandManager * old;
#line 80 "/shotwell/src/CommandManager.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_COMMAND_MANAGER));
#line 80 "/shotwell/src/CommandManager.vala"
	old = value->data[0].v_pointer;
#line 80 "/shotwell/src/CommandManager.vala"
	if (v_object) {
#line 80 "/shotwell/src/CommandManager.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_COMMAND_MANAGER));
#line 80 "/shotwell/src/CommandManager.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 80 "/shotwell/src/CommandManager.vala"
		value->data[0].v_pointer = v_object;
#line 80 "/shotwell/src/CommandManager.vala"
		command_manager_ref (value->data[0].v_pointer);
#line 1167 "CommandManager.c"
	} else {
#line 80 "/shotwell/src/CommandManager.vala"
		value->data[0].v_pointer = NULL;
#line 1171 "CommandManager.c"
	}
#line 80 "/shotwell/src/CommandManager.vala"
	if (old) {
#line 80 "/shotwell/src/CommandManager.vala"
		command_manager_unref (old);
#line 1177 "CommandManager.c"
	}
}


void value_take_command_manager (GValue* value, gpointer v_object) {
	CommandManager * old;
#line 80 "/shotwell/src/CommandManager.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_COMMAND_MANAGER));
#line 80 "/shotwell/src/CommandManager.vala"
	old = value->data[0].v_pointer;
#line 80 "/shotwell/src/CommandManager.vala"
	if (v_object) {
#line 80 "/shotwell/src/CommandManager.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_COMMAND_MANAGER));
#line 80 "/shotwell/src/CommandManager.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 80 "/shotwell/src/CommandManager.vala"
		value->data[0].v_pointer = v_object;
#line 1196 "CommandManager.c"
	} else {
#line 80 "/shotwell/src/CommandManager.vala"
		value->data[0].v_pointer = NULL;
#line 1200 "CommandManager.c"
	}
#line 80 "/shotwell/src/CommandManager.vala"
	if (old) {
#line 80 "/shotwell/src/CommandManager.vala"
		command_manager_unref (old);
#line 1206 "CommandManager.c"
	}
}


static void command_manager_class_init (CommandManagerClass * klass) {
#line 80 "/shotwell/src/CommandManager.vala"
	command_manager_parent_class = g_type_class_peek_parent (klass);
#line 80 "/shotwell/src/CommandManager.vala"
	((CommandManagerClass *) klass)->finalize = command_manager_finalize;
#line 80 "/shotwell/src/CommandManager.vala"
	g_type_class_add_private (klass, sizeof (CommandManagerPrivate));
#line 80 "/shotwell/src/CommandManager.vala"
	command_manager_signals[COMMAND_MANAGER_ALTERED_SIGNAL] = g_signal_new ("altered", TYPE_COMMAND_MANAGER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__BOOLEAN_BOOLEAN, G_TYPE_NONE, 2, G_TYPE_BOOLEAN, G_TYPE_BOOLEAN);
#line 1220 "CommandManager.c"
}


static void command_manager_instance_init (CommandManager * self) {
	GeeArrayList* _tmp0_;
	GeeArrayList* _tmp1_;
#line 80 "/shotwell/src/CommandManager.vala"
	self->priv = COMMAND_MANAGER_GET_PRIVATE (self);
#line 84 "/shotwell/src/CommandManager.vala"
	_tmp0_ = gee_array_list_new (TYPE_COMMAND, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
#line 84 "/shotwell/src/CommandManager.vala"
	self->priv->undo_stack = _tmp0_;
#line 85 "/shotwell/src/CommandManager.vala"
	_tmp1_ = gee_array_list_new (TYPE_COMMAND, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
#line 85 "/shotwell/src/CommandManager.vala"
	self->priv->redo_stack = _tmp1_;
#line 80 "/shotwell/src/CommandManager.vala"
	self->ref_count = 1;
#line 1239 "CommandManager.c"
}


static void command_manager_finalize (CommandManager * obj) {
	CommandManager * self;
#line 80 "/shotwell/src/CommandManager.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_COMMAND_MANAGER, CommandManager);
#line 80 "/shotwell/src/CommandManager.vala"
	g_signal_handlers_destroy (self);
#line 84 "/shotwell/src/CommandManager.vala"
	_g_object_unref0 (self->priv->undo_stack);
#line 85 "/shotwell/src/CommandManager.vala"
	_g_object_unref0 (self->priv->redo_stack);
#line 1253 "CommandManager.c"
}


GType command_manager_get_type (void) {
	static volatile gsize command_manager_type_id__volatile = 0;
	if (g_once_init_enter (&command_manager_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_command_manager_init, value_command_manager_free_value, value_command_manager_copy_value, value_command_manager_peek_pointer, "p", value_command_manager_collect_value, "p", value_command_manager_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (CommandManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) command_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CommandManager), 0, (GInstanceInitFunc) command_manager_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType command_manager_type_id;
		command_manager_type_id = g_type_register_fundamental (g_type_fundamental_next (), "CommandManager", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&command_manager_type_id__volatile, command_manager_type_id);
	}
	return command_manager_type_id__volatile;
}


gpointer command_manager_ref (gpointer instance) {
	CommandManager * self;
	self = instance;
#line 80 "/shotwell/src/CommandManager.vala"
	g_atomic_int_inc (&self->ref_count);
#line 80 "/shotwell/src/CommandManager.vala"
	return instance;
#line 1278 "CommandManager.c"
}


void command_manager_unref (gpointer instance) {
	CommandManager * self;
	self = instance;
#line 80 "/shotwell/src/CommandManager.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 80 "/shotwell/src/CommandManager.vala"
		COMMAND_MANAGER_GET_CLASS (self)->finalize (self);
#line 80 "/shotwell/src/CommandManager.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 1291 "CommandManager.c"
	}
}



