/* shotwell-authenticator.vapi generated by valac 0.34.7, do not modify. */

namespace Publishing {
	namespace Authenticator {
		namespace Shotwell {
			namespace Facebook {
			}
			namespace Flickr {
			}
			namespace Google {
			}
		}
		[CCode (cheader_filename = "shotwell-authenticator.h")]
		public class Factory : Spit.Publishing.AuthenticatorFactory, GLib.Object {
			public Factory ();
			public static Publishing.Authenticator.Factory get_instance ();
		}
	}
}
